name: Publish

on: create

jobs:
  publish:
    name: Publish to JSR
    if: github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: npm i -g wasm-pack
      - run: just publish
